// utils/stateFromPincode.js
const PINCODE_STATE_MAP = {
  "11": { name: "DELHI", code: "07" },
  "12": { name: "HARYANA", code: "06" },
  "13": { name: "HARYANA", code: "06" },
  "14": { name: "PUNJAB", code: "03" },
  "15": { name: "PUNJAB", code: "03" },
  "16": { name: "PUNJAB", code: "03" },
  "17": { name: "HIMACHAL PRADESH", code: "02" },
  "18": { name: "JAMMU AND KASHMIR", code: "01" },
  "19": { name: "JAMMU AND KASHMIR", code: "01" },
  "20": { name: "UTTAR PRADESH", code: "09" },
  "21": { name: "UTTAR PRADESH", code: "09" },
  "22": { name: "UTTAR PRADESH", code: "09" },
  "23": { name: "UTTAR PRADESH", code: "09" },
  "24": { name: "UTTAR PRADESH", code: "09" },
  "25": { name: "UTTAR PRADESH", code: "09" },
  "26": { name: "UTTAR PRADESH", code: "09" },
  "27": { name: "UTTAR PRADESH", code: "09" },
  "28": { name: "UTTAR PRADESH", code: "09" },
  "30": { name: "RAJASTHAN", code: "08" },
  "31": { name: "RAJASTHAN", code: "08" },
  "32": { name: "RAJASTHAN", code: "08" },
  "33": { name: "RAJASTHAN", code: "08" },
  "34": { name: "RAJASTHAN", code: "08" },
  "36": { name: "GUJARAT", code: "24" },
  "37": { name: "GUJARAT", code: "24" },
  "38": { name: "GUJARAT", code: "24" },
  "39": { name: "GUJARAT", code: "24" },
  "40": { name: "MAHARASHTRA", code: "27" },
  "41": { name: "MAHARASHTRA", code: "27" },
  "42": { name: "MAHARASHTRA", code: "27" },
  "43": { name: "MAHARASHTRA", code: "27" },
  "44": { name: "MAHARASHTRA", code: "27" },
  "45": { name: "MADHYA PRADESH", code: "23" },
  "46": { name: "MADHYA PRADESH", code: "23" },
  "47": { name: "MADHYA PRADESH", code: "23" },
  "48": { name: "MADHYA PRADESH", code: "23" },
  "49": { name: "CHHATTISGARH", code: "22" },
  "50": { name: "TELANGANA", code: "36" },
  "51": { name: "TELANGANA", code: "36" },
  "52": { name: "ANDHRA PRADESH", code: "37" },
  "53": { name: "ANDHRA PRADESH", code: "37" },
  "56": { name: "KARNATAKA", code: "29" },
  "57": { name: "KARNATAKA", code: "29" },
  "58": { name: "KARNATAKA", code: "29" },
  "59": { name: "KARNATAKA", code: "29" },
  "60": { name: "TAMIL NADU", code: "33" },
  "61": { name: "TAMIL NADU", code: "33" },
  "62": { name: "TAMIL NADU", code: "33" },
  "63": { name: "TAMIL NADU", code: "33" },
  "64": { name: "TAMIL NADU", code: "33" },
  "67": { name: "KERALA", code: "32" },
  "68": { name: "KERALA", code: "32" },
  "69": { name: "KERALA", code: "32" },
  "70": { name: "WEST BENGAL", code: "19" },
  "71": { name: "WEST BENGAL", code: "19" },
  "72": { name: "WEST BENGAL", code: "19" },
  "73": { name: "WEST BENGAL", code: "19" },
  "74": { name: "WEST BENGAL", code: "19" },
  "75": { name: "ODISHA", code: "21" },
  "76": { name: "ODISHA", code: "21" },
  "77": { name: "ODISHA", code: "21" },
  "78": { name: "ASSAM", code: "18" },
  "80": { name: "BIHAR", code: "10" },
  "81": { name: "BIHAR", code: "10" },
  "82": { name: "BIHAR", code: "10" },
  "83": { name: "JHARKHAND", code: "20" },
  "84": { name: "JHARKHAND", code: "20" },
  "85": { name: "JHARKHAND", code: "20" },
  "90": { name: "ARMY POST OFFICE", code: "00" },
};

export function getStateFromPincode(pincode) {
  if (!pincode || String(pincode).length < 2) {
    return { name: "UTTAR PRADESH", code: "09" };
  }
  const prefix = String(pincode).substring(0, 2);
  return PINCODE_STATE_MAP[prefix] || { name: "UTTAR PRADESH", code: "09" };
}
